Revert "Merge branch 'NOAA-EMC:develop' into develop"
This reverts commit 8a4d2385b30f640cc13029cbe21697e492f03844, reversing
changes made to 70ef79fed16972caaf547399c8988b4841170f56.

diff --git a/model/bin/w3_make b/model/bin/w3_make
--- a/model/bin/w3_make
+++ b/model/bin/w3_make
@@ -117,22 +117,24 @@
     exit 1
   fi
 
-  # src dir
-  makefile=$main_dir/src/makefile
-  if [ ! -d $main_dir/src ]
+  # ftn dir
+  makefile=$main_dir/ftn/makefile
+  if [ ! -d $main_dir/ftn ]
   then
     echo ' '
-    echo "[ERROR] Directory $main_dir/src not found"
+    echo "[ERROR] Directory $main_dir/ftn not found"
     echo '        Please check the content of your directory model'
     exit 1
   fi
   rm -f $makefile
 
-# 1.e Set regular and netCDF progs - - - - - - - - - - - - - - - - - - - - - -
-# reg_programs = non-NetCDF programs
-# cdf_programs = NetCDF programs
 
-  #STRT BOUND OUTF OUTP TRCK GRIB GINT GX* UPRSTR
+
+
+# 1.e Set regular and netCDF progs - - - - - - - - - - - - - - - - - - - - - -
+
+# GRID STRT BOUND OUTF OUTP TRCK GRIB GINT GX* UPRSTR LIBWW3
+#  reg_programs = non-NetCDF programs
   reg_programs="ww3_strt"
   reg_programs="$reg_programs ww3_bound"
   reg_programs="$reg_programs ww3_outf"
@@ -144,7 +146,8 @@
   reg_programs="$reg_programs gx_outp"
   reg_programs="$reg_programs ww3_uprstr" 
 
-  # PRNC OUNF OUNP BOUNC TRNC
+# PRNC OUNF OUNP BOUNC TRNC
+# cdf_programs = NetCDF programs
   cdf_programs="ww3_prnc"
   cdf_programs="$cdf_programs ww3_ounf"
   cdf_programs="$cdf_programs ww3_ounp"
@@ -157,7 +160,14 @@
     cdf_programs="$cdf_programs ww3_prtide"
   fi
 
-  # MULTI MULTI_ESMF SBS1 LIBWW3
+  # NCEP GRIB
+  export ncep_grib_compile="no"
+  if [ -n "`grep NCEP $switch_file`" ]
+  then
+    export ncep_grib_compile="yes"
+  fi
+
+  # MULTI MULTI_ESMF SBS1
   if [ -n "`grep SCRIPNC $switch_file`" ] || [ -n "`grep OASIS $switch_file`" ]  || [ -n "`grep PDLIB $switch_file`" ]
   then
     cdf_programs="$cdf_programs ww3_grid"
@@ -183,11 +193,18 @@
   if [ -n "`grep TRKNC $switch_file`" ]
   then
     cdf_programs="$cdf_programs ww3_systrk"
+    systrck_nc4notrknc=0
   else
-    reg_programs="$reg_programs ww3_systrk"
+    if [ -n "`grep NC4 $switch_file`" ]
+    then
+      systrck_nc4notrknc=1
+    else
+      systrck_nc4notrknc=0
+      reg_programs="$reg_programs ww3_systrk"
+    fi
   fi
 
-  # PREP GSPL
+  # SHEL PREP GSPL
   if [ -n "`grep OASIS $switch_file`" ] || [ -n "`grep PDLIB $switch_file`" ]
   then
     cdf_programs="$cdf_programs ww3_gspl"
@@ -197,7 +214,6 @@
     reg_programs="$reg_programs ww3_prep"
   fi
 
-  #SHEL 
   if [ -n "`grep OASIS $switch_file`" ]  || [ -n "`grep PDLIB $switch_file`" ]
   then
     cdf_programs="$cdf_programs ww3_shel"
@@ -205,7 +221,6 @@
     reg_programs="$reg_programs ww3_shel"
   fi
 
-  #Shared Object
   if [ -n "`grep -nri fPIC $comp_file`" ]
   then
     reg_programs="$reg_programs libww3.so"
@@ -213,9 +228,31 @@
     echo 'Shared Object     : No'
   fi
 
-# 1.f Set sequential or parallel folders - - - - - - - - - - - - - - - - - - -
+  # if no progs in argument
+  if [ -z "$all_programs" ]
+  then
+    if [ -z "$WWATCH3_NETCDF" ]
+    then
+      all_programs="$reg_programs"
+    else
+      all_programs="$reg_programs $cdf_programs"
+    fi
+  fi
+  echo ' '
+  echo "[INFO] list of the programs selected : $all_programs"
+
+
+# 1.f sort sequential and parallel programs - - - - - - - - - - - - - - - - - -
+
+  # no filtering is done to distinguish sequential to parallel programs 
+  # see w3_automake for this feature
+  progs=$all_programs
+
+
+# 1.e Set sequential or parallel folders - - - - - - - - - - - - - - - - - - -
 
   flag_SHRD=`grep SHRD $switch_file | wc -l | awk '{ print $1}'`
+  flag_OMPX=`grep OMPX $switch_file | wc -l | awk '{ print $1}'`
   flag_OMPH=`grep OMPH $switch_file | wc -l | awk '{ print $1}'`
 
   switch_file_old=$main_dir/bin/switch.old
@@ -226,12 +263,12 @@
 
   if [ "$flag_SHRD" -gt '0' ]
   then
-    pres_type='SEQ'
-    flag_OMP=`grep OMP $switch_file | wc -l | awk '{ print $1}'`
-    if [ "$flag_OMP" -gt '0' ]
-    then 
+    if [ "$flag_OMPX" -gt '0' ]
+    then
       pres_type='OMP'
-    fi 
+    else
+      pres_type='SEQ'
+    fi
   else
     if [ "$flag_OMPH" -gt '0' ]
     then
@@ -257,72 +294,149 @@
 
 
 
-# 1.g Setup for NetCDF compile - - - - - - - - - - - - - - - - - - - - - - - - 
+# 1.c Setup for NetCDF compile - - - - - - - - - - - - - - - - - - - - - - - - 
 
-# 1.g.1 NetCDF compile message function
+# 1.c.1 NetCDF compile message function
 
   netcdf_compile_message () {
 
   cat 2>&1 << 'EOF'
 
-***********************************************************************
-***         WAVEWATCH III NetCDF Compile Instructions               ***
-***********************************************************************
+*****************************************************************
+***         WAVEWATCH III NetCDF Compile Instructions         ***
+*****************************************************************
 
-For compiling with NetCDF, the following environment variable
-is required:
+Compile of WAVEWATCH III NetCDF enabled programs requires the
+environment variable WWATCH3_NETCDF be set to either NC3 (compile
+with NetCDF version 3.x) or NC4 (compile with NetCDF version 4.x).
+
+If WWATCH3_NETCDF = NC3, then the following environment variables
+are required.
+
+    NETCDF_LIBDIR = <path to NetCDF-3 libraries>
+    NETCDF_INCDIR = <path to NetCDF-3 include>
+
+If WWATCH3_NETCDF = NC4, then the following environment variables
+are required.
 
     NETCDF_CONFIG = <path to NetCDF-4 nc-config utility>
 
 The nc-config utility (part of the NetCDF-4 install) is used to
-determine the appropriate compile and link flags.
+determine the appropriate compile and link flags for the
+WWATCH3_NETCDF=NC4 compile.
 
-For NetCDF routines to compile, WAVEWATCH III requires 
-NetCDF version 4.1.1 or higher. Use "nc-config --version" to check 
-the version of the installed NetCDF. It is also required for NetCDF 
-to be compiled with the NetCDF-4 API enabled. Use "nc-config --has-nc4" 
-to check if the installed NetCDF has the NetCDF-4 API enabled.
+The NetCDF-4 compile requires NetCDF version 4.1.1 or higher.
+Use "nc-config --version" to check the version of the installed
+NetCDF.
 
-***********************************************************************
+Compiling with the NC4 switch requires WWATCH3_NETCDF=NC4 and the
+NetCDF-4 installation compiled with the NetCDF-4 API enabled.
+Use "nc-config --has-nc4" to check if the installed NetCDF has
+the NetCDF-4 API enabled.
+
+*****************************************************************
 
 EOF
 
   }
 
-# 1.g.2 NetCDF check compile environment function
+# 1.c.2 NetCDF check compile environment function
 
   netcdf_check_compile () {
 
   mode=$1 #must be ERROR or WARNING
 
-  if [ -z "$NETCDF_CONFIG" ]
+  if [ -z "$WWATCH3_NETCDF" ]
   then
     netcdf_compile_message
-    echo "$mode: NETCDF_CONFIG not defined"; echo ' '
+    echo "$mode: WWATCH3_NETCDF not defined"; echo ' '
     return 1
-  fi
-  if [ ! -x "$NETCDF_CONFIG" ]
-  then
-    netcdf_compile_message
-    echo "$mode: $NETCDF_CONFIG does not exist or is not executable"; echo ' '
-    return 1
-  fi
-  netcdf_version=`$NETCDF_CONFIG --version | awk '{print $2}'`
-  if [ -z "`echo $netcdf_version | cut -d. -f3`" ]
-  then
-    netcdf_version="$netcdf_version.0"
-  fi
-  if [ `echo $netcdf_version | tr -d . | tr -d - | tr -d 'A-Z a-z'` -lt 411 ]
-  then
-    netcdf_compile_message
-    echo "$mode: NetCDF version $netcdf_version < 4.1.1"; echo ' '
-    return 1
+  else
+    case $WWATCH3_NETCDF in
+      NC3)
+        if [ -z "$NETCDF_LIBDIR" ]
+        then
+          netcdf_compile_message
+          echo "$mode: NETCDF_LIBDIR not defined"; echo ' '
+          return 1
+        fi
+        if [ -z "$NETCDF_INCDIR" ]
+        then
+          netcdf_compile_message
+          echo "$mode: NETCDF_INCDIR not defined"; echo ' '
+          return 1
+        fi
+      ;;
+      NC4)
+        if [ ! -n "`grep NC4 $switch_file`" ]
+        then
+          echo "WARNING: NC4 is set in WWATCH3_NETCDF but not in the switch file"; echo ' '
+#          return 1
+        fi
+        if [ -z "$NETCDF_CONFIG" ]
+        then
+          netcdf_compile_message
+          echo "$mode: NETCDF_CONFIG not defined"; echo ' '
+          return 1
+        fi
+        if [ ! -x "$NETCDF_CONFIG" ]
+        then
+          netcdf_compile_message
+          echo "$mode: $NETCDF_CONFIG does not exist or is not executable"; echo ' '
+          return 1
+        fi
+        netcdf_version=`$NETCDF_CONFIG --version | awk '{print $2}'`
+        if [ -z "`echo $netcdf_version | cut -d. -f3`" ]
+        then
+          netcdf_version="$netcdf_version.0"
+        fi
+        if [ `echo $netcdf_version | tr -d . | tr -d - | tr -d 'A-Z a-z'` -lt 411 ]
+        then
+          netcdf_compile_message
+          echo "$mode: NetCDF version $netcdf_version < 4.1.1"; echo ' '
+          return 1
+        fi
+      ;;
+      *)
+        netcdf_compile_message
+        echo "$mode: WWATCH3_NETCDF=$WWATCH3_NETCDF not supported"; echo ' '
+        return 1
+      ;;
+    esac
   fi
 
   return 0
   }
 
-# 1.g.3 Check for NetCDF compile
+# 1.c.3 NetCDF check api function
+
+  netcdf_check_api () {
+
+  mode=$1 #must be ERROR or WARNING
+
+  if [ -n "`grep NC4 $switch_file`" ]
+  then
+    case $WWATCH3_NETCDF in
+      NC3)
+        netcdf_compile_message
+        echo "$mode: WWATCH3_NETCDF=NC3 incompatible with NC4 switch"; echo ' '
+        return 1
+      ;;
+      NC4)
+        if [ "`$NETCDF_CONFIG --has-nc4`" = 'no' ]
+        then
+          netcdf_compile_message
+          echo "$mode: NetCDF-4 API not enabled (required by NC4 switch)"; echo ' '
+          return 1
+        fi
+      ;;
+    esac
+  fi
+
+  return 0
+  }
+
+# 1.c.4 Check for NetCDF compile
 
   if [ $default_mode -eq 1 ]
   then
@@ -330,10 +444,13 @@ EOF
     then
       echo "NetCDF enabled programs ($cdf_programs)"
       echo "will not be compiled unless NetCDF compile environment is properly set."; echo ' '
+      if [ $systrck_nc4notrknc -eq 1 ] 
+      then 
+         echo "WARNING: ww3_systrk will not be compiled due to invalid switch option."; echo ' '
+         echo "TRKNC switch is also required with NC4."; echo ' '
+      fi 
       echo "Continuing with compile of non-NetCDF programs ..."; echo ' '
-      all_programs="$reg_programs"
-    else 
-      all_programs="$reg_programs $cdf_programs"
+      progs="$reg_programs"
     fi
   else
     nc_compile=0
@@ -354,18 +471,23 @@ EOF
         exit 1
       fi
     fi
+    systrkprog="ww3_systrk"
+    for prog in $systrkprog
+    do
+      if [ -n "`echo $progs | grep $prog`" ]
+      then   
+        if [ $systrck_nc4notrknc -eq 1 ]
+        then
+          echo "ERROR: ww3_systrk will not be compiled due to invalid switch option."; echo ' '
+          echo "TRKNC switch is also required with NC4."; echo ' '
+          echo "Now exiting ..."; echo ' '
+          exit 1
+        fi
+      fi
+    done
   fi
 
-  echo ' '
-  echo "[INFO] list of the programs selected : $all_programs"
-
-
-# 1.h set progs list   - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-  # no filtering is done to distinguish sequential to parallel programs 
-  progs=$all_programs
-
-# 1.i Prepare scratch directory  - - - - - - - - - - - - - - - - - - - - - - - 
+# 1.d Prepare scratch directory  - - - - - - - - - - - - - - - - - - - - - - - 
 
   if test ! -d $temp_dir
   then
@@ -385,14 +507,14 @@ EOF
   then
     rm -f *.l
   fi
-  cd $main_dir/src
+  cd $main_dir/ftn
 
-# 1.j Prepare makefile - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# 1.e Prepare makefile - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
   make_make='y'
   if test -f $switch_file_old
   then
-    if test -f $main_dir/src/makefile && \
+    if test -f $main_dir/ftn/makefile && \
        test -z "`diff $switch_file $switch_file_old`"
     then
       make_make='n'
@@ -406,11 +528,11 @@ EOF
     then
       if [ "$flag_SHRD" -gt '0' ]
       then
-        if [ "$flag_OMP" -gt '0' ]
+        if [ "$flag_OMPX" -gt '0' ]
         then
           cp $switch_file ${switch_file_old}_OMP
           cp $makefile ${makefile}_OMP
-        else 
+        else
           cp $switch_file ${switch_file_old}_SEQ
           cp $makefile ${makefile}_SEQ
         fi
@@ -430,7 +552,7 @@ EOF
   fi
   echo ' '
 
-# 1.k Export paths - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
+# 1.f Export paths - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
 
   aPb="$main_dir/bin"     # path containing shell scripts
   aPo="$main_dir/obj"     # path containing .o files
@@ -506,17 +628,7 @@ EOF
       fi
       export pdlib_mod
 
-      # NCEP GRIB
-      export ncep_grib_compile="no"
-      #check for switch file: 
-      if [ -n "`grep NCEP $switch_file`" ]
-      then
-        #only set to yes if compiling ww3_grib: 
-        if [ -n "`echo $prog | grep ww3_grib`" ]
-        then
-          export ncep_grib_compile="yes"
-        fi 
-      fi
+
 
       # if esmf is included in program name, then the compile
       # requires DIST switch and the ESMFMKFILE is
